=== weixingLuo/rule-engine/rule-engine-core/src/test/java/top/after/rule/engine/script/decision.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="decision">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datasource">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string"></xs:attribute>
                        <xs:attribute name="code" type="xs:string"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="domain-variable"></xs:element>
                <xs:element ref="define" />
                <xs:element ref="rule-set" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="define">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="action" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="domain-variable">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="object" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="fields" minOccurs="0" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="optional"></xs:attribute>
                        <xs:attribute name="code" type="xs:string" use="optional"></xs:attribute>
                        <xs:attribute name="type" type="xs:string" use="optional"></xs:attribute>
                        <xs:attribute name="visibility" type="xs:string" default="visible"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="fields">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="field" minOccurs="0" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="field">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="options" minOccurs="0" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute name="name"></xs:attribute>
            <xs:attribute name="type" use="optional"></xs:attribute>
            <xs:attribute name="code" use="optional"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="rule-set">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="rule" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="domain" use="optional"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="rule">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:element ref="switch" minOccurs="1" maxOccurs="1" />
                <xs:element></xs:element>
            </xs:choice>
            <xs:attribute name="type"></xs:attribute>
            <xs:attribute name="name"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="switch">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="parameter" minOccurs="1" maxOccurs="1" />
                <xs:element name="case" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="operator" type="operatorTypeModel" />
                            <xs:element ref="parameter" minOccurs="1" maxOccurs="1" />
                            <xs:element ref="action" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                        <xs:attribute name="id" use="optional"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="action" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="action">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="switch" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
            <xs:attribute name="ref" type="string" use="optional"></xs:attribute>
            <xs:attribute name="type" type="actionTypeModel" use="optional"></xs:attribute>
            <xs:attribute name="with-param" type="string" use="optional"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="parameter">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:element ref="operation" minOccurs="0" maxOccurs="1"></xs:element>
                <xs:element ref="options" minOccurs="0" maxOccurs="1"></xs:element>
            </xs:choice>
            <xs:attribute name="value-type" type="parameterTypeModel" use="required"></xs:attribute>
            <xs:attribute name="name-type" type="parameterNameTypeModel" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="options">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="option" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="name"></xs:attribute>
                        <xs:attribute name="code"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="selected"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="operation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="parameter"></xs:element>
                <xs:element name="operator" type="operatorTypeModel" />
                <xs:element ref="parameter"></xs:element>
            </xs:sequence>
            <xs:attribute name="result-type" type="resultTypeModel" />
            <xs:attribute name="operation-type" type="operationTypeModel" />
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="operationTypeModel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="unary_operation" />
            <xs:enumeration value="binary_operation" />
            <xs:enumeration value="..." />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="actionTypeModel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="enum" />
            <xs:enumeration value="switch" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="operatorTypeModel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="加上" />
            <xs:enumeration value="减去" />
            <xs:enumeration value="乘以" />
            <xs:enumeration value="除以" />
            <xs:enumeration value="等于" />
            <xs:enumeration value="不等于" />
            <xs:enumeration value="大于" />
            <xs:enumeration value="大于等于" />
            <xs:enumeration value="小于" />
            <xs:enumeration value="小于等于" />
            <xs:enumeration value="早于" />
            <xs:enumeration value="早于等于" />
            <xs:enumeration value="晚于" />
            <xs:enumeration value="晚于等于" />
            <xs:enumeration value="前几天" />
            <xs:enumeration value="后几天" />
            <xs:enumeration value="在列表中" />
            <xs:enumeration value="包含列表中词汇" />
            <xs:enumeration value="不为空" />
            <xs:enumeration value="为空" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="parameterTypeModel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string" />
            <xs:enumeration value="number" />
            <xs:enumeration value="date">
                <xs:annotation>
                    <xs:documentation>格式：yyyy-MM-dd</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="list" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="parameterNameTypeModel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="input" />
            <xs:enumeration value="enum" />
            <xs:enumeration value="variable">
                <xs:annotation>
                    <xs:documentation>
						the variable parameters are from datasource!
					</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="operation" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="resultTypeModel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="boolean" />
            <xs:enumeration value="number" />
            <xs:enumeration value="date" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== weixingLuo/rule-engine/rule-engine-core/src/test/java/top/after/rule/engine/script/decision.xml
<?xml version="1.0" encoding="UTF-8" ?>
<decision xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./decision.xsd">
    <datasource name="申请单" code="apply" />
    <domain-variable>
        <object name="申请单" type="domainObject">
            <fields>
                <field name="申请人内部黑名单" type="string" code="innder_black" />
                <field name="申请人年龄" type="number" code="age" />
                <field name="工作单位" type="number" code="comany" />
                <field name="IP地址所在城市与工作所在城市" type="enum" code="same_ip_address">
                    <options>
                        <option code="1" name="一致" />
                        <option code="2" name="不一致" />
                    </options>
                </field>
                <field name="GPS城市与工作城市一致" type="string" code="same_gps_address" />
            </fields>
        </object>
        <object name="审批详情" type="domainObject">
            <fields>
                <field name="审批结果" type="enum" code="audit-result">
                    <options>
                        <option code="1" name="通过" />
                        <option code="2" name="转人工" />
                        <option code="3" name="拒绝" />
                    </options>
                </field>
            </fields>
        </object>
    </domain-variable>
    <define>
        <action type="setter" code="set-audit-result">
            <!--      <setter type="constructor">
                <object name="审批结果" type="enum" code="audit-result">
                    <options>
                        <option code="1" name="通过" />
                        <option code="2" name="转人工" />
                        <option code="3" name="拒绝" />
                    </options>
                </object> 
            </setter>-->
        </action>
    </define>
    <rule-set domain="申请单">
        <rule type="switch" name="申请人内部黑名单">
            <switch>
                <parameter name-type="variable" value-type="string">申请人内部黑名单</parameter>
                <case>
                    <operator>等于</operator>
                    <parameter name-type="enum" value-type="string">
                        <options selected="2">
                            <option name="是" code="1" />
                            <option name="否" code="2" />
                        </options>
                    </parameter>
                    <action type="enum" ref="set-audit-result" with-param="1" />
                </case>
                <case>
                    <operator>等于</operator>
                    <parameter name-type="enum" value-type="string">
                        <options selected="1">
                            <option name="是" code="1" />
                            <option name="否" code="2" />
                        </options>
                    </parameter>
                    <action type="enum" ref="set-audit-result" with-param="3" />
                </case>
                <action type="enum" ref="set-audit-result" with-param="1" />
            </switch>
        </rule>
        <rule type="switch" name="申请人年龄">
            <switch>
                <parameter name-type="variable" value-type="number">申请人年龄</parameter>
                <case>
                    <operator>小于</operator>
                    <parameter name-type="enum" value-type="number">18</parameter>
                    <action type="enum" ref="set-audit-result" with-param="3" />
                </case>
                <case>
                    <operator>大于</operator>
                    <parameter name-type="enum" value-type="number">18</parameter>
                    <action type="enum" ref="set-audit-result" with-param="3" />
                </case>
                <action type="enum" ref="set-audit-result" with-param="1" />
            </switch>
        </rule>
        <rule type="switch" name="工作单位">
            <switch>
                <parameter name-type="variable" value-type="number">工作单位</parameter>
                <case>
                    <operator>包含列表中词汇</operator>
                    <parameter value-type="list" name-type="input">金融信息,平安普惠,信和财富</parameter>
                    <action type="enum" ref="set-audit-result" with-param="3" />
                </case>
                <action type="enum" ref="set-audit-result" with-param="1" />
            </switch>
        </rule>
        <rule type="switch" name="IP城市与工作城市一致">
            <switch>
                <parameter name-type="variable" value-type="string">IP地址所在城市与工作所在城市</parameter>
                <case id="3">
                    <operator>等于</operator>
                    <parameter name-type="enum" value-type="string">
                        <options selected="1">
                            <option name="是" code="1" />
                            <option name="否" code="2" />
                        </options>
                    </parameter>
                    <action type="enum" ref="set-audit-result" with-param="1" />
                </case>
                <case id="4">
                    <operator>等于</operator>
                    <parameter name-type="enum" value-type="string">
                        <options selected="2">
                            <option name="是" code="1" />
                            <option name="否" code="2" />
                        </options>
                    </parameter>
                    <action type="switch">
                        <switch>
                            <parameter name-type="variable" value-type="string">GPS城市与工作城市一致</parameter>
                            <case>
                                <operator>等于</operator>
                                <parameter name-type="enum" value-type="string">
                                    <options selected="1">
                                        <option name="是" code="1" />
                                        <option name="否" code="2" />
                                    </options>
                                </parameter>
                                <action type="enum" ref="set-audit-result" with-param="1" />
                            </case>
                            <action type="enum" ref="set-audit-result" with-param="3" />
                        </switch>
                    </action>
                </case>
                <action type="enum" ref="set-audit-result" with-param="1" />
            </switch>
        </rule>
    </rule-set>
</decision>
